{{- if eq ( lower .Values.mode ) "cronjob" }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 8 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote}}
  {{- with .Values.cronjob.cronjobSpec }}
  {{- toYaml . | nindent 2}}
  {{- end }}
  jobTemplate:
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "helm.labels" . | nindent 8 }}
    spec:
      {{- with .Values.cronjob.jobSpec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "helm.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.rbac.enable }}
          serviceAccountName: {{ .Release.Name }}
          {{- else }}
          serviceAccountName: default
          automountServiceAccountToken: false
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Release.Name }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: {{ .Values.image }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              env:
                - name: __PODNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: __NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: PYTHONUNBUFFERED
                  value: "1"
                {{- with .Values.env }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- with .Values.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.ports }}
              ports:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.startupProbe }}
              startupProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.livenessProbe }}
              livenessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.readinessProbe }}
              readinessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: script
                  mountPath: {{ .Values.scriptDir }}
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: script
              configMap:
                name: {{ .Release.Name }}
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
